### ISSUE TITLE
the code is crashing with opencv4 

### ISSUE THREAD

**Issue by peererror** [nwesem/facenet_cpp_tensorflow#1]
there is a crash with opencv4 in code on following line 

`croppedFaces[i] = croppedFaces[i] - cv::Vec3d(mean_pxl, mean_pxl, mean_pxl);
`
with assert on 
` CV_Assert(type2 == CV_64F && (sz2.height == 1 || sz2.height == 4));`

please help to fix the issue

**Comment by nwesem** [comment]
thank you for letting me know. As stated in the README, I tested this project with OpenCV 3.x. As soon as I upgrade to OpenCV 4, I will take care of this. If you have a fix for this, I would be happy to include your changes into the project.

**Comment by peererror** [comment]
#2

**Comment by nwesem** [comment]
great! i just checked for backward compatibility and everything is working fine with opencv 3.4. thanks a lot for this quick fix!
